# Generated by Django 2.1.5 on 2021-08-05 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20210804_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='browsedBook',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 18, 9, 35, 930197)),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
