# Generated by Django 2.2.5 on 2021-08-05 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20210805_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 1, 38, 5, 773283)),
        ),
    ]
